"""normalize resume metadata

Revision ID: 014c2f87fe37
Revises: 0004_resumes_metadata_table
Create Date: 2026-05-07 01:06:30.881156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '014c2f87fe37'
down_revision: Union[str, None] = '0004_resumes_metadata_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'chats', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column(table_name='resumes_metadata', column_name='location', new_column_name='raw_location')
    op.add_column('resumes_metadata', sa.Column('state', sa.VARCHAR(length=255), nullable=True))
    op.drop_constraint('uq_file_path_resume_name', 'resumes_metadata', type_='unique')
    op.create_foreign_key(None, 'resumes_metadata', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes_metadata', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'resumes_metadata', type_='foreignkey')
    op.create_unique_constraint('uq_file_path_resume_name', 'resumes_metadata', ['file_path', 'resume_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('resumes_metadata', 'state')
    op.alter_column(table_name='resumes_metadata', column_name='raw_location', new_column_name='location')
    op.drop_constraint(None, 'history', type_='foreignkey')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    # ### end Alembic commands ###
