"""Added chat_group_id column to History table

Revision ID: 2189b45b07cd
Revises: 3a9f89f494b0
Create Date: 2026-05-07 03:53:10.407733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2189b45b07cd'
down_revision: Union[str, None] = '3a9f89f494b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('chat_group_id', sa.UUID(), nullable=True))
    op.create_index('idx_history_chat_group_id', 'history', ['chat_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_history_chat_group_id', table_name='history')
    op.drop_column('history', 'chat_group_id')
    # ### end Alembic commands ###
