"""Added city column to resume_metadata table

Revision ID: 3a9f89f494b0
Revises: 014c2f87fe37
Create Date: 2026-05-07 01:15:35.714232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a9f89f494b0'
down_revision: Union[str, None] = '014c2f87fe37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes_metadata', sa.Column('city', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes_metadata', 'city')
    # ### end Alembic commands ###
