"""New table user_resumes and changed old table resume_metadata to resumes

Revision ID: 84777312b323
Revises: 89497766548b
Create Date: 2026-05-09 04:59:37.531237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84777312b323'
down_revision: Union[str, None] = '89497766548b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('resumes_metadata', 'resumes')

    op.create_table('user_resumes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    op.execute("""
    INSERT INTO user_resumes (id, user_id, resume_id)
    SELECT gen_random_uuid(), user_id, id
    FROM resumes
    """)

    op.drop_column('resumes', 'user_id')

    

    op.create_index('idx_user_resumes_resume_id', 'user_resumes', ['resume_id'], unique=False)
    op.create_index('idx_user_resumes_user_id', 'user_resumes', ['user_id'], unique=False)
    
    op.execute("""
    ALTER INDEX idx_resumes_metadata_file_path RENAME TO idx_resumes_file_path;
    """)    
    ### end Alembic commands ###


def downgrade() -> None:
    ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('resumes', 'resumes_metadata')
    op.add_column('resumes_metadata',sa.Column('user_id', sa.UUID(), nullable=True))

    op.execute("""
    UPDATE resumes_metadata rm
    SET user_id = ur.user_id
    FROM user_resumes ur
    WHERE ur.resume_id = rm.id
    """)
    op.alter_column('resumes_metadata','user_id',nullable=False)
    op.create_foreign_key(
    'resumes_metadata_user_id_fkey',
    'resumes_metadata',
    'users',
    ['user_id'],
    ['id'],
    ondelete='CASCADE'
    )

    op.drop_index('idx_user_resumes_user_id', table_name='user_resumes')
    op.drop_index('idx_user_resumes_resume_id', table_name='user_resumes')
    op.drop_table('user_resumes')

    op.execute("""
    ALTER INDEX idx_resumes_file_path RENAME TO idx_resumes_metadata_file_path;
    """)

    ### end Alembic commands ###
