"""Added new column summarized_history to history table

Revision ID: 89497766548b
Revises: 2189b45b07cd
Create Date: 2026-05-08 23:51:08.091173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89497766548b'
down_revision: Union[str, None] = '2189b45b07cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('summarized_history', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'summarized_history')
    # ### end Alembic commands ###
